# Generated by Django 2.0.4 on 2018-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
