# Generated by Django 2.0.4 on 2018-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_path',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
